from __future__ import annotations

import json
from pathlib import Path

from pricing_mlops.io.artifacts import write_artifact_manifest
from pricing_mlops.io.csv import read_csv_rows, write_csv_rows
from pricing_mlops.io.filesystem import copy_tree
from pricing.auth_monitoring.artifact_contract import (
    expected_auth_monitoring_artifacts,
    validate_expected_monitoring_artifacts,
)
from pricing.auth_monitoring.config import AuthMonitoringConfig
from pricing.auth_monitoring.rules.operational_decision import (
    OperationalDecisionResult,
    calculate_operational_decision,
)
from pricing.types import Row


def run_operational_decision_step(
    *,
    input_dir: str | Path,
    output_dir: str | Path,
    run_id: str,
    config: AuthMonitoringConfig | None = None,
) -> OperationalDecisionResult:
    input_dir = Path(input_dir)
    output_dir = Path(output_dir)
    copy_tree(input_dir, output_dir)
    result = calculate_operational_decision(
        run_id=run_id,
        validity_log=read_csv_rows(input_dir / "logs" / "auth_recommendation_validity_log.csv"),
        validity_revenue_summary=read_csv_rows(input_dir / "summaries" / "validity_revenue_summary.csv"),
        new_combo_log=_read_optional_csv(input_dir / "logs" / "new_combo_without_baseline_recommendation_log.csv"),
        data_quality_log=_read_optional_csv(input_dir / "logs" / "data_quality_log.csv"),
        recommendation_coverage_log=_read_optional_csv(input_dir / "logs" / "recommendation_coverage_log.csv"),
        catalog_bin_coverage_log=_read_optional_csv(input_dir / "logs" / "catalog_bin_coverage_log.csv"),
        input_history_drift_log=_read_optional_csv(input_dir / "logs" / "auth_history_drift_log.csv"),
        config=config,
    )
    write_csv_rows(output_dir / "summaries" / "run_readiness_summary.csv", [result.run_readiness_summary])
    write_csv_rows(output_dir / "summaries" / "operational_decision_summary.csv", [result.operational_decision_summary])
    _write_notification_payload(output_dir, result)
    _write_recommendation_validity_report(output_dir, result)
    write_artifact_manifest(output_dir, run_id)
    _validate_output_contract(output_dir)
    return result


def _read_optional_csv(path: Path) -> list[Row]:
    return read_csv_rows(path) if path.exists() else []


def _write_notification_payload(output_dir: Path, result: OperationalDecisionResult) -> None:
    summary = result.operational_decision_summary
    notification = _notification_context(result)
    payload = {
        "schema_version": "auth_monitoring_notification_v1",
        "run_id": summary["drift_run_id"],
        "severity": notification["severity"],
        "should_notify": notification["should_notify"],
        "blocking_decision": notification["blocking_decision"],
        "title": notification["title"],
        "status": result.run_readiness_summary["run_readiness_status"],
        "recommended_operational_action": summary["recommended_operational_action"],
        "primary_reason": notification["primary_reason"],
        "next_action_owner": notification["next_action_owner"],
        "decision_rationale": summary["decision_rationale"],
        "signals": _decision_signals(summary),
    }
    output_path = output_dir / "summaries" / "notification_payload.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _write_recommendation_validity_report(output_dir: Path, result: OperationalDecisionResult) -> None:
    output_path = output_dir / "reports" / "auth_recommendation_validity_report.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    summary = result.operational_decision_summary
    run_summary = result.run_readiness_summary
    notification = _notification_context(result)
    output_path.write_text(
        "\n".join(
            [
                "# AUTH Recommendation Validity Report",
                "",
                "## Operational Decision",
                "",
                f"- Status: {run_summary['run_readiness_status']}",
                f"- Notification severity: {notification['severity']}",
                f"- Blocking decision: {notification['blocking_decision']}",
                f"- Recommended operational action: {summary['recommended_operational_action']}",
                f"- Next action owner: {notification['next_action_owner']}",
                "",
                "## Signal Summary",
                "",
                "| Signal | Status |",
                "|---|---|",
                *[
                    f"| {signal_name} | {signal_status} |"
                    for signal_name, signal_status in _decision_signals(summary).items()
                ],
                "",
                "## Recommended Next Step",
                "",
                summary["decision_rationale"],
                "",
                "This report is generated by the Azure ML operational decision step from the "
                "notebook-derived monitoring artifacts.",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _notification_context(result: OperationalDecisionResult) -> Row:
    status = str(result.run_readiness_summary["run_readiness_status"])
    action = str(result.operational_decision_summary["recommended_operational_action"])
    rationale = str(result.operational_decision_summary["decision_rationale"])
    severity = _notification_severity(status)
    return {
        "severity": severity,
        "should_notify": severity in {"critical", "warning"},
        "blocking_decision": status == "Red",
        "title": f"Pricing AUTH monitoring: {status} decision",
        "primary_reason": _primary_reason(rationale),
        "next_action_owner": _next_action_owner(action),
    }


def _notification_severity(run_readiness_status: str) -> str:
    return {
        "Red": "critical",
        "Yellow": "warning",
        "Watch": "watch",
        "Green": "none",
    }.get(run_readiness_status, "watch")


def _primary_reason(decision_rationale: str) -> str:
    return decision_rationale.split(";")[0].strip().rstrip(".") + "."


def _next_action_owner(recommended_operational_action: str) -> str:
    if "DATA_QUALITY" in recommended_operational_action:
        return "Data Engineering"
    if "CATALOG" in recommended_operational_action:
        return "Catalog Owner"
    if "HB_SVI" in recommended_operational_action or "RETRAINING" in recommended_operational_action:
        return "ML Owner"
    if "SCORING" in recommended_operational_action or "RECOMMENDATION" in recommended_operational_action:
        return "Pricing PM"
    return "Pricing PM"


def _decision_signals(summary: Row) -> dict[str, object]:
    return {
        "price_drift_status": summary["price_drift_status"],
        "recommendation_validity_global_status": summary["recommendation_validity_global_status"],
        "recommendation_coverage_status": summary["recommendation_coverage_status"],
        "catalog_bin_coverage_status": summary["catalog_bin_coverage_status"],
        "auth_history_drift_status": summary["auth_history_drift_status"],
    }


def _validate_output_contract(output_dir: Path) -> None:
    artifacts = {
        name: artifact
        for name, artifact in expected_auth_monitoring_artifacts().items()
        if name not in {"simulated_operational_handoff", "simulated_operational_handoff_report"}
    }
    validation = validate_expected_monitoring_artifacts(output_dir, artifacts=artifacts)
    if validation.is_complete:
        return
    missing = ", ".join(str(record["relative_path"]) for record in validation.missing_required)
    raise FileNotFoundError(f"AUTH monitoring output contract is incomplete; missing: {missing}")
