from __future__ import annotations

from pathlib import Path

from pricing_mlops.io.artifacts import write_artifact_manifest
from pricing_mlops.io.csv import read_csv_rows, write_csv_rows
from pricing_mlops.io.filesystem import copy_tree
from pricing.auth_monitoring.artifact_contract import validate_expected_monitoring_artifacts
from pricing.auth_monitoring.config import AuthMonitoringConfig
from pricing.auth_monitoring.rules.operational_decision import (
    OperationalDecisionResult,
    calculate_operational_decision,
)
from pricing.types import Row


def run_operational_decision_step(
    *,
    input_dir: str | Path,
    output_dir: str | Path,
    run_id: str,
    config: AuthMonitoringConfig | None = None,
) -> OperationalDecisionResult:
    input_dir = Path(input_dir)
    output_dir = Path(output_dir)
    copy_tree(input_dir, output_dir)
    result = calculate_operational_decision(
        run_id=run_id,
        validity_log=read_csv_rows(input_dir / "logs" / "auth_recommendation_validity_log.csv"),
        validity_revenue_summary=read_csv_rows(input_dir / "summaries" / "validity_revenue_summary.csv"),
        new_combo_log=_read_optional_csv(input_dir / "logs" / "new_combo_without_baseline_recommendation_log.csv"),
        data_quality_log=_read_optional_csv(input_dir / "logs" / "data_quality_log.csv"),
        recommendation_coverage_log=_read_optional_csv(input_dir / "logs" / "recommendation_coverage_log.csv"),
        catalog_bin_coverage_log=_read_optional_csv(input_dir / "logs" / "catalog_bin_coverage_log.csv"),
        input_history_drift_log=_read_optional_csv(input_dir / "logs" / "auth_history_drift_log.csv"),
        config=config,
    )
    write_csv_rows(output_dir / "summaries" / "run_readiness_summary.csv", [result.run_readiness_summary])
    write_csv_rows(output_dir / "summaries" / "operational_decision_summary.csv", [result.operational_decision_summary])
    _write_recommendation_validity_report(output_dir, result)
    write_artifact_manifest(output_dir, run_id)
    _validate_output_contract(output_dir)
    return result


def _read_optional_csv(path: Path) -> list[Row]:
    return read_csv_rows(path) if path.exists() else []


def _write_recommendation_validity_report(output_dir: Path, result: OperationalDecisionResult) -> None:
    output_path = output_dir / "reports" / "auth_recommendation_validity_report.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "\n".join(
            [
                "# AUTH Recommendation Validity Report",
                "",
                f"- Run readiness status: {result.run_readiness_summary['run_readiness_status']}",
                "- Recommended operational action: "
                f"{result.operational_decision_summary['recommended_operational_action']}",
                "- HB/SVI retraining recommendation: "
                f"{result.operational_decision_summary['hb_svi_retraining_recommendation']}",
                "",
                "This report is generated by the Azure ML operational decision step from the "
                "notebook-derived monitoring artifacts.",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _validate_output_contract(output_dir: Path) -> None:
    validation = validate_expected_monitoring_artifacts(output_dir)
    if validation.is_complete:
        return
    missing = ", ".join(str(record["relative_path"]) for record in validation.missing_required)
    raise FileNotFoundError(f"AUTH monitoring output contract is incomplete; missing: {missing}")
