$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: pricing-mlops-runtime
version: 0.1.0
description: Versioned runtime for Pricing MLOps analytical Azure ML components.
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
conda_file: conda.yml
